---
languageCode: ko
languageName: 한국어
params:
  cover:
    responsiveImages: true
    linkFullImages: false
  profileMode:
    enabled: true
    imageUrl: "/images/profile.png"
    imageTitle: my memoji
    title: 안녕하세요, 저는 Jesús입니다
    subtitle: 저는 테스트 분야의 소프트웨어 개발자 엔지니어입니다.
weight: 3
taxonomies:
  tag: tags
title: Jesús Fernández Jiménez - SDET and Tech Enthusiast
description: "I'm an SDET specializing in Ecommerce. On this website, I share experiences about technology, web development, quality assurance, and more."
