---
languageCode: es-es
languageName: Español
params:
  cover:
    responsiveImages: true
    linkFullImages: false
  dateFormat: 02 January 2006
  profileMode:
    enabled: true
    imageUrl: "/images/profile.png"
    imageTitle: my memoji
    title: Hola, soy Jesús
    subtitle: Soy *Software Developer Engineer in Test*.
weight: 3
taxonomies:
  tag: tags
title: Jesús Fernández Jiménez - SDET y entusiasta de la tecnología
description: "Soy un SDET especialidado en Ecommerce. En esta web, comparto experiencias sobre tecnología, desarrollo web, QA y más."
