---
languageCode: es-an
languageName: Andalûh
params:
  description: "Çoy QA Engineer. En êtta wêh, comparto êpperiençiâ çobre tênnolohía, deçarroyo wêh, QA y mâh."
  cover:
    responsiveImages: true
    linkFullImages: false
  dateFormat: 02 January 2006
  profileMode:
    enabled: true
    imageUrl: "/images/profile.png"
    imageTitle: my memoji
    title: Ola, çoy Heçûh
    subtitle: "*QA Engineer* @ [TROOP](https://trooptravel.com)."
weight: 2
taxonomies:
  tag: tags
title: Jesús Fernández Jiménez - QA Engineer y entuçiâtta de la tênnolohía
