---
languageCode: es-an
languageName: Andalûh
params:
  cover:
    responsiveImages: true
    linkFullImages: false
  dateFormat: 02 January 2006
  profileMode:
    enabled: true
    imageUrl: "/images/profile.png"
    imageTitle: my memoji
    title: Ola, çoy Heçûh
    subtitle: Çoy *Software Developer Engineer in Test* en [e2y](https://e2ycommerce.com/).
weight: 2
taxonomies:
  tag: tags
title: Jesús Fernández Jiménez - SDET y entuçiâtta de la tênnolohía
description: "Çoy un SDET êppeçialidao en Ecômmerçe. En êtta wêh, comparto êpperiençiâ çobre tênnolohía, deçarroyo wêh, QA y mâh."
