---
languageCode: es-es
languageName: Español
params:
  description: "Soy QA Engineer. En esta web, comparto experiencias sobre tecnología, desarrollo web, QA y más."
  cover:
    responsiveImages: true
    linkFullImages: false
  dateFormat: 02 January 2006
  profileMode:
    enabled: true
    imageUrl: "/images/profile.png"
    imageTitle: my memoji
    title: Hola, soy Jesús
    subtitle: "*QA Engineer* @ [TROOP](https://trooptravel.com)."
weight: 3
taxonomies:
  tag: tags
title: Jesús Fernández Jiménez - QA Engineer y entusiasta de la tecnología
