---
main:
- name: Home
  identifier: home
  url: "/"
  weight: 1
- name: Blog
  identifier: blog
  url: "/blog/"
  weight: 5
- name: Projects
  identifier: projects
  url: "/projects/"
  weight: 6
- name: Search
  identifier: search
  url: "/search/"
  weight: 7
