---
repository: https://github.com/jesusfj710/jesusfj710.github.io
author: Jesús Fernández Jiménez
defaultTheme: auto
customTextFontFamily: Atkinson Hyperlegible
customCodeFontFamily: Fira Code
displayFullLangName: true
disableThemeToggle: false
ShowBreadCrumbs: false
ShowCodeCopyButtons: true
DisableAnchoredHeadings: true
ShowShareButtons: false
ShowToc: false

ShowFullTextinRSS: true
# disableThemeToggle: true
ShowReadingTime: true
# disableSpecial1stPost: true
ShowPostNavLinks: true
ShowRssButtonInSectionTermList: true
# comments: false

socialIcons:
  - name: github
    url: https://github.com/jesusfj710
  - name: linkedin
    url: https://www.linkedin.com/in/jesusfj710
  - name: protonmail
    url: mailto:jesusfj710@proton.me
  - name: pgpkey
    url: https://raw.githubusercontent.com/jesusfj710/jesusfj710/main/PGP/publickey.jesusfj710%40proton.me-816b42d401517d459be24aae1b31d9d930a4ab1c.asc
assets:
  favicon: "/images/favicon.ico"
  favicon16x16: "/images/favicon-16x16.png"
  favicon32x32: "/images/favicon-32x32.png"
  apple_touch_icon: "/images/apple-touch-icon.png"
  safari_pinned_tab: "/images/apple-touch-icon.png"

cover: 
  linkFullImages: true
  responsiveImages: true

fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  # location: 0
  # distance: 1000
  threshold: 0.2
  # minMatchCharLength: 2
  keys: ["title", "permalink", "summary", "content", "tags"]

label:
  text: 🤖
